version: "3.8"

services:
  mmd_db:
    image: postgres:16
    container_name: mmd_db
    volumes:
      - mmd_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  mmd_db:

networks:
  mmd_data_network:
