version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
  #   depends_on:
  #     - mmd
  # mmd:
  #   build: ./back
  #   container_name: mmd
  #   command: bundle exec rails s -p 3000 -b '0.0.0.0' -e staging;
  #   depends_on:
  #     - mmd_db
  #   # links:
  #   #   - redis
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env

  mmd_db:
    image: postgres:16
    container_name: mmd_db
    volumes:
      - mmd_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  # mmd_redis:
  #   image: redis:4.0.12-alpine
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - mmd_redis:/data

volumes:
  mmd_db:
  # mmd_redis:
networks:
  mmd_data_network:
